@WebScrapingProject.Server_HostAddress = http://localhost:5043

GET {{WebScrapingProject.Server_HostAddress}}/weatherforecast/
Accept: application/json

### MongoDB Baglanti Testi
POST {{WebScrapingProject.Server_HostAddress}}/api/news/test-connection
###
